name: DevSecOps CI/CD Pipeline

on:
  push:
    branches: ["main"]

jobs:
  security:
    runs-on: ubuntu-latest

    permissions:
      issues: write
      contents: read
      actions: write

    steps:

    - name: Checkout Repo
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.9"

    - name: Install requirements
      run: pip install -r flask-app/requirements.txt

    - name: Run Bandit Security Scan
      run: |
        pip install bandit
        bandit -r flask-app/--exit-zero

    - name: Build Docker image
      run: docker build -t flask-app ./flask-app

    - name: Run Trivy scan
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: flask-app
        severity: CRITICAL,HIGH
        format: table
        exit-code: 0

    - name: Install Checkov
      run: pip install checkov

    - name: Scan Terraform
      run: checkov -d terraform/

    - name: Run Flask Container
      run: |
        docker build -t flask-app ./flask-app
        docker run -d -p 5001:5001 --name flask-app flask-app

    - name: Wait for app
      run: sleep 10

    - name: Check running containers
      run: docker ps

    - name: OWASP ZAP scan
      uses: zaproxy/action-baseline@v0.12.0
      with:
        target:target: "http://host.docker.internal:5001"
        cmd_options: '-a'
        artifact_name: zap-scan-report
        allow_issue_writing: false


    - name: Upload ZAP Report
      uses: actions/upload-artifact@v4
      with:
        name: zap-report
        path: |
          report_html.html
          report_json.json
          report_md.md